seed: 0
device: 0
experiment_name: TUM
model: 
  n_components: 100_000
  init_random: True
  dof: 1
  scale: ${model.n_components}
  use_reassign: True
  reassign_fraction: 0.01
data: 
  model_name: tum
  data_path: /home/shared/rgbd_dataset_freiburg3_long_office_household
  subsample_factor: null
train: 
  batch_size: 500
  learning_rate: 1.0
  beta: 0.0
  n_iters: 1
dirname: ${experiment_name}/${data.model_name}/nc:${model.n_components}/randinit:${model.init_random}_reassign:${model.use_reassign}
hydra: 
  job: 
    chdir: True
  run: 
    dir: data/${dirname}
  sweep: 
    dir: data/sweep/${dirname}
    subdir: ""